
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=${BACKEND_URL}
    volumes:
      - ./frontend:/app
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CLOUD_PROVIDER=${CLOUD_PROVIDER}
    volumes:
      - ./backend:/app
    restart: unless-stopped
