version: '3.8'

services:
  vault:
    build: .
    container_name: honeypotfarm-vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    volumes:
      - vault-data:/vault
    restart: unless-stopped

volumes:
  vault-data: